# Site settings
title: APES
email: info@biom.uni-freiburg.de
description: Advice for Problems in Environmental Statistics
baseurl: /APES
url: http://biometry.github.io/APES/
username: biometry

# Build settings
# permalink: pretty

# kramdown options
kramdown:
  input: GFM

highlighter: pygments

# Excludes
exclude: ['*.sublime*', 'Gemfile*', 'feed.xml', '*.Rmd', '*.rmd']

# github gems
# gems:
#   - jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      author: "Florian Hartig"
